[2025-03-31T13:54:04.866+0530] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-31T13:54:04.872+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: check_dag.check_file_exists scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-03-31T13:54:04.876+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: check_dag.check_file_exists scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-03-31T13:54:04.876+0530] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-03-31T13:54:04.885+0530] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): check_file_exists> on 2025-03-30 00:00:00+00:00
[2025-03-31T13:54:04.886+0530] {standard_task_runner.py:72} INFO - Started process 20682 to run task
[2025-03-31T13:54:04.889+0530] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'check_dag', 'check_file_exists', 'scheduled__2025-03-30T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/check_dag.py', '--cfg-path', '/tmp/tmp7xjyyqm3']
[2025-03-31T13:54:04.890+0530] {standard_task_runner.py:105} INFO - Job 19: Subtask check_file_exists
[2025-03-31T13:54:04.919+0530] {task_command.py:467} INFO - Running <TaskInstance: check_dag.check_file_exists scheduled__2025-03-30T00:00:00+00:00 [running]> on host Voldemort.
[2025-03-31T13:54:04.961+0530] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='check_dag' AIRFLOW_CTX_TASK_ID='check_file_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T00:00:00+00:00'
[2025-03-31T13:54:04.962+0530] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-31T13:54:04.970+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-31T13:54:04.971+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'test -f /tmp/dummy']
[2025-03-31T13:54:04.975+0530] {subprocess.py:86} INFO - Output:
[2025-03-31T13:54:04.976+0530] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-31T13:54:04.988+0530] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-31T13:54:04.988+0530] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=check_dag, task_id=check_file_exists, run_id=scheduled__2025-03-30T00:00:00+00:00, execution_date=20250330T000000, start_date=20250331T082404, end_date=20250331T082404
[2025-03-31T13:54:05.021+0530] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-31T13:54:05.031+0530] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-31T13:54:05.034+0530] {local_task_job_runner.py:245} INFO - ::endgroup::
