[2025-05-19T19:43:21.579+0530] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-19T19:43:21.587+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_taxi_etl.load_to_snowflake manual__2025-05-19T14:12:03.718893+00:00 [queued]>
[2025-05-19T19:43:21.592+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_taxi_etl.load_to_snowflake manual__2025-05-19T14:12:03.718893+00:00 [queued]>
[2025-05-19T19:43:21.593+0530] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-05-19T19:43:21.606+0530] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): load_to_snowflake> on 2025-05-19 14:12:03.718893+00:00
[2025-05-19T19:43:21.609+0530] {standard_task_runner.py:72} INFO - Started process 30417 to run task
[2025-05-19T19:43:21.614+0530] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'nyc_taxi_etl', 'load_to_snowflake', 'manual__2025-05-19T14:12:03.718893+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/nyc_taxi_etl.py', '--cfg-path', '/tmp/tmp_c7qayee']
[2025-05-19T19:43:21.616+0530] {standard_task_runner.py:105} INFO - Job 83: Subtask load_to_snowflake
[2025-05-19T19:43:21.642+0530] {task_command.py:467} INFO - Running <TaskInstance: nyc_taxi_etl.load_to_snowflake manual__2025-05-19T14:12:03.718893+00:00 [running]> on host Voldemort.
[2025-05-19T19:43:21.694+0530] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='nyc_taxi_etl' AIRFLOW_CTX_TASK_ID='load_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T14:12:03.718893+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-19T14:12:03.718893+00:00'
[2025-05-19T19:43:21.694+0530] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-19T19:43:21.702+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-19T19:43:21.703+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/opt/spark/bin/spark-submit /home/pranav_shirali/airflow-project/scripts/ETL/load.py']
[2025-05-19T19:43:21.708+0530] {subprocess.py:86} INFO - Output:
[2025-05-19T19:43:23.102+0530] {subprocess.py:93} INFO - 25/05/19 19:43:23 WARN Utils: Your hostname, Voldemort resolves to a loopback address: 127.0.1.1; using 10.255.255.254 instead (on interface lo)
[2025-05-19T19:43:23.105+0530] {subprocess.py:93} INFO - 25/05/19 19:43:23 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2025-05-19T19:43:23.938+0530] {subprocess.py:93} INFO - 25/05/19 19:43:23 INFO SparkContext: Running Spark version 3.5.5
[2025-05-19T19:43:23.939+0530] {subprocess.py:93} INFO - 25/05/19 19:43:23 INFO SparkContext: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-05-19T19:43:23.939+0530] {subprocess.py:93} INFO - 25/05/19 19:43:23 INFO SparkContext: Java version 11.0.27
[2025-05-19T19:43:23.993+0530] {subprocess.py:93} INFO - 25/05/19 19:43:23 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-19T19:43:24.062+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO ResourceUtils: ==============================================================
[2025-05-19T19:43:24.063+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-05-19T19:43:24.063+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO ResourceUtils: ==============================================================
[2025-05-19T19:43:24.064+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO SparkContext: Submitted application: NYC Taxi Load to Snowflake
[2025-05-19T19:43:24.081+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-05-19T19:43:24.089+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO ResourceProfile: Limiting resource is cpu
[2025-05-19T19:43:24.090+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-05-19T19:43:24.129+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO SecurityManager: Changing view acls to: pranav_shirali
[2025-05-19T19:43:24.130+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO SecurityManager: Changing modify acls to: pranav_shirali
[2025-05-19T19:43:24.130+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO SecurityManager: Changing view acls groups to:
[2025-05-19T19:43:24.130+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO SecurityManager: Changing modify acls groups to:
[2025-05-19T19:43:24.131+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: pranav_shirali; groups with view permissions: EMPTY; users with modify permissions: pranav_shirali; groups with modify permissions: EMPTY
[2025-05-19T19:43:24.350+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO Utils: Successfully started service 'sparkDriver' on port 40127.
[2025-05-19T19:43:24.374+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO SparkEnv: Registering MapOutputTracker
[2025-05-19T19:43:24.403+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO SparkEnv: Registering BlockManagerMaster
[2025-05-19T19:43:24.419+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-05-19T19:43:24.419+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-05-19T19:43:24.422+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-05-19T19:43:24.444+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-26d7581c-731d-4dec-9f86-31a4003a2f05
[2025-05-19T19:43:24.456+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-05-19T19:43:24.466+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-05-19T19:43:24.572+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-05-19T19:43:24.614+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-05-19T19:43:24.688+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO Executor: Starting executor ID driver on host 10.255.255.254
[2025-05-19T19:43:24.688+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO Executor: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-05-19T19:43:24.688+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO Executor: Java version 11.0.27
[2025-05-19T19:43:24.693+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-05-19T19:43:24.694+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@c75733c for default.
[2025-05-19T19:43:24.710+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 33121.
[2025-05-19T19:43:24.710+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO NettyBlockTransferService: Server created on 10.255.255.254:33121
[2025-05-19T19:43:24.712+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-05-19T19:43:24.716+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 10.255.255.254, 33121, None)
[2025-05-19T19:43:24.719+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO BlockManagerMasterEndpoint: Registering block manager 10.255.255.254:33121 with 434.4 MiB RAM, BlockManagerId(driver, 10.255.255.254, 33121, None)
[2025-05-19T19:43:24.720+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 10.255.255.254, 33121, None)
[2025-05-19T19:43:24.721+0530] {subprocess.py:93} INFO - 25/05/19 19:43:24 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 10.255.255.254, 33121, None)
[2025-05-19T19:43:25.166+0530] {subprocess.py:93} INFO - 25/05/19 19:43:25 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-05-19T19:43:25.174+0530] {subprocess.py:93} INFO - 25/05/19 19:43:25 INFO SharedState: Warehouse path is 'file:/tmp/airflowtmpqamddyfh/spark-warehouse'.
[2025-05-19T19:43:26.436+0530] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-19T19:43:26.436+0530] {subprocess.py:93} INFO -   File "/home/pranav_shirali/airflow-project/scripts/ETL/load.py", line 6, in <module>
[2025-05-19T19:43:26.437+0530] {subprocess.py:93} INFO -     trip_df = spark.read.parquet("/home/pranav_shirali/airflow-project/scripts/etl/nyc_taxi_trip.parquet")
[2025-05-19T19:43:26.437+0530] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 544, in parquet
[2025-05-19T19:43:26.437+0530] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-05-19T19:43:26.437+0530] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-05-19T19:43:26.444+0530] {subprocess.py:93} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/home/pranav_shirali/airflow-project/scripts/etl/nyc_taxi_trip.parquet.
[2025-05-19T19:43:26.496+0530] {subprocess.py:93} INFO - 25/05/19 19:43:26 INFO SparkContext: Invoking stop() from shutdown hook
[2025-05-19T19:43:26.497+0530] {subprocess.py:93} INFO - 25/05/19 19:43:26 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-05-19T19:43:26.506+0530] {subprocess.py:93} INFO - 25/05/19 19:43:26 INFO SparkUI: Stopped Spark web UI at http://10.255.255.254:4040
[2025-05-19T19:43:26.521+0530] {subprocess.py:93} INFO - 25/05/19 19:43:26 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-05-19T19:43:26.531+0530] {subprocess.py:93} INFO - 25/05/19 19:43:26 INFO MemoryStore: MemoryStore cleared
[2025-05-19T19:43:26.531+0530] {subprocess.py:93} INFO - 25/05/19 19:43:26 INFO BlockManager: BlockManager stopped
[2025-05-19T19:43:26.536+0530] {subprocess.py:93} INFO - 25/05/19 19:43:26 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-05-19T19:43:26.539+0530] {subprocess.py:93} INFO - 25/05/19 19:43:26 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-05-19T19:43:26.546+0530] {subprocess.py:93} INFO - 25/05/19 19:43:26 INFO SparkContext: Successfully stopped SparkContext
[2025-05-19T19:43:26.546+0530] {subprocess.py:93} INFO - 25/05/19 19:43:26 INFO ShutdownHookManager: Shutdown hook called
[2025-05-19T19:43:26.547+0530] {subprocess.py:93} INFO - 25/05/19 19:43:26 INFO ShutdownHookManager: Deleting directory /tmp/spark-d27076c9-3b64-4bda-9975-f5ce29ce38da/pyspark-d5b084a2-e3ae-4ffe-8c16-809542be6545
[2025-05-19T19:43:26.551+0530] {subprocess.py:93} INFO - 25/05/19 19:43:26 INFO ShutdownHookManager: Deleting directory /tmp/spark-bceca309-7a01-481e-a970-fdd7083e40d2
[2025-05-19T19:43:26.553+0530] {subprocess.py:93} INFO - 25/05/19 19:43:26 INFO ShutdownHookManager: Deleting directory /tmp/spark-d27076c9-3b64-4bda-9975-f5ce29ce38da
[2025-05-19T19:43:26.580+0530] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-19T19:43:26.586+0530] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-19T19:43:26.589+0530] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=nyc_taxi_etl, task_id=load_to_snowflake, run_id=manual__2025-05-19T14:12:03.718893+00:00, execution_date=20250519T141203, start_date=20250519T141321, end_date=20250519T141326
[2025-05-19T19:43:26.598+0530] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-19T19:43:26.599+0530] {standard_task_runner.py:124} ERROR - Failed to execute job 83 for task load_to_snowflake (Bash command failed. The command returned a non-zero exit code 1.; 30417)
Traceback (most recent call last):
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pranav_shirali/airflow-project/airflow-env/lib/python3.10/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-19T19:43:26.639+0530] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-19T19:43:26.647+0530] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-19T19:43:26.648+0530] {local_task_job_runner.py:245} INFO - ::endgroup::
