[2025-03-31T13:53:59.395+0530] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-31T13:53:59.403+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: check_dag.create_file scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-03-31T13:53:59.407+0530] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: check_dag.create_file scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-03-31T13:53:59.407+0530] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-03-31T13:53:59.418+0530] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): create_file> on 2025-03-30 00:00:00+00:00
[2025-03-31T13:53:59.420+0530] {standard_task_runner.py:72} INFO - Started process 20632 to run task
[2025-03-31T13:53:59.423+0530] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'check_dag', 'create_file', 'scheduled__2025-03-30T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/check_dag.py', '--cfg-path', '/tmp/tmp866lg0rf']
[2025-03-31T13:53:59.424+0530] {standard_task_runner.py:105} INFO - Job 17: Subtask create_file
[2025-03-31T13:53:59.449+0530] {task_command.py:467} INFO - Running <TaskInstance: check_dag.create_file scheduled__2025-03-30T00:00:00+00:00 [running]> on host Voldemort.
[2025-03-31T13:53:59.487+0530] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='check_dag' AIRFLOW_CTX_TASK_ID='create_file' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T00:00:00+00:00'
[2025-03-31T13:53:59.487+0530] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-31T13:53:59.499+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-31T13:53:59.500+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Hi there!" >/tmp/dummy']
[2025-03-31T13:53:59.504+0530] {subprocess.py:86} INFO - Output:
[2025-03-31T13:53:59.505+0530] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-31T13:53:59.516+0530] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-31T13:53:59.517+0530] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=check_dag, task_id=create_file, run_id=scheduled__2025-03-30T00:00:00+00:00, execution_date=20250330T000000, start_date=20250331T082359, end_date=20250331T082359
[2025-03-31T13:53:59.555+0530] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-31T13:53:59.570+0530] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-31T13:53:59.573+0530] {local_task_job_runner.py:245} INFO - ::endgroup::
